DROP TABLE DIM_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE DIM_PRODUTO CASCADE CONSTRAINTS;

DROP TABLE DIM_TEMPO CASCADE CONSTRAINTS;

DROP TABLE DIM_VENDEDOR CASCADE CONSTRAINTS;

DROP TABLE FATO_VENDAS CASCADE CONSTRAINTS;

CREATE TABLE DIM_CLIENTE (
    COD_CLIENTE NUMBER PRIMARY KEY,
    NOM_CLIENTE VARCHAR2(50) NOT NULL
);

CREATE TABLE DIM_PRODUTO (
    COD_PRODUTO NUMBER PRIMARY KEY,
    NOM_PRODUTO VARCHAR2(100) NOT NULL,
    STA_ATIVO CHAR(1) NOT NULL
);

CREATE TABLE DIM_TEMPO (
    COD_TEMPO NUMBER PRIMARY KEY,
    ANO NUMBER NOT NULL,
    MES NUMBER NOT NULL,
    DIA NUMBER NOT NULL
);

CREATE TABLE DIM_VENDEDOR (
    COD_VENDEDOR NUMBER PRIMARY KEY,
    NOM_VENDEDOR VARCHAR2(50) NOT NULL
);

CREATE TABLE FATO_VENDAS (
    COD_VENDA NUMBER PRIMARY KEY,
    COD_CLIENTE NUMBER,
    COD_PRODUTO NUMBER,
    COD_TEMPO NUMBER,
    COD_VENDEDOR NUMBER,
    QTD_VENDIDA NUMBER NOT NULL,
    VALOR_TOTAL NUMBER(12, 2) NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES DIM_CLIENTE(COD_CLIENTE),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES DIM_PRODUTO(COD_PRODUTO),
    CONSTRAINT FK_TEMPO FOREIGN KEY (COD_TEMPO) REFERENCES DIM_TEMPO(COD_TEMPO),
    CONSTRAINT FK_VENDEDOR FOREIGN KEY (COD_VENDEDOR) REFERENCES DIM_VENDEDOR(COD_VENDEDOR)
);