
CREATE TABLE AUDITORIA_DIMENSOES (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    NOME_TABELA VARCHAR2(100),
    OPERACAO VARCHAR2(10),
    DATA_OPERACAO DATE,
    USUARIO VARCHAR2(50),
    DADOS_INSERIDOS VARCHAR2(4000)
);


CREATE SEQUENCE AUDITORIA_DIMENSOES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER AUDIT_INSERT_DIM_CLIENTE
AFTER INSERT ON DIM_CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_DIMENSOES (
        ID_AUDITORIA,
        NOME_TABELA,
        OPERACAO,
        DATA_OPERACAO,
        USUARIO,
        DADOS_INSERIDOS
    ) 
    VALUES (
        AUDITORIA_DIMENSOES_SEQ.NEXTVAL,
        'DIM_CLIENTE',
        'INSERT',
        SYSDATE,
        USER,
        'COD_CLIENTE=' || :NEW.COD_CLIENTE || ', NOM_CLIENTE=' || :NEW.NOM_CLIENTE
    );
END;
/

CREATE OR REPLACE TRIGGER AUDIT_INSERT_DIM_PRODUTO
AFTER INSERT ON DIM_PRODUTO
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_DIMENSOES (
        ID_AUDITORIA,
        NOME_TABELA,
        OPERACAO,
        DATA_OPERACAO,
        USUARIO,
        DADOS_INSERIDOS
    ) 
    VALUES (
        AUDITORIA_DIMENSOES_SEQ.NEXTVAL,
        'DIM_PRODUTO',
        'INSERT',
        SYSDATE,
        USER,
        'COD_PRODUTO=' || :NEW.COD_PRODUTO || ', NOM_PRODUTO=' || :NEW.NOM_PRODUTO || ', STA_ATIVO=' || :NEW.STA_ATIVO
    );
END;
/


CREATE OR REPLACE TRIGGER AUDIT_INSERT_DIM_VENDEDOR
AFTER INSERT ON DIM_VENDEDOR
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_DIMENSOES (
        ID_AUDITORIA,
        NOME_TABELA,
        OPERACAO,
        DATA_OPERACAO,
        USUARIO,
        DADOS_INSERIDOS
    ) 
    VALUES (
        AUDITORIA_DIMENSOES_SEQ.NEXTVAL,
        'DIM_VENDEDOR',
        'INSERT',
        SYSDATE,
        USER,
        'COD_VENDEDOR=' || :NEW.COD_VENDEDOR || ', NOM_VENDEDOR=' || :NEW.NOM_VENDEDOR
    );
END;
/


CREATE OR REPLACE TRIGGER AUDIT_INSERT_DIM_TEMPO
AFTER INSERT ON DIM_TEMPO
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_DIMENSOES (
        ID_AUDITORIA,
        NOME_TABELA,
        OPERACAO,
        DATA_OPERACAO,
        USUARIO,
        DADOS_INSERIDOS
    ) 
    VALUES (
        AUDITORIA_DIMENSOES_SEQ.NEXTVAL,
        'DIM_TEMPO',
        'INSERT',
        SYSDATE,
        USER,
        'COD_TEMPO=' || :NEW.COD_TEMPO || ', ANO=' || :NEW.ANO || ', MES=' || :NEW.MES || ', DIA=' || :NEW.DIA
    );
END;
/
